export const items = [
  // --- ORGANIC (Marrón) ---
  {
    name_es: 'Cáscara de fruta',
    name_en: 'Fruit peel',
    name_ca: 'Pela de fruita',
    container_type: 'OrganicContainer',
    keywords_es: ['fruta', 'comida', 'piel', 'banana', 'plátano', 'cascara', 'cáscara', 'cáscara de fruta', 'naranja', 'mandarina', 'mango'],
    keywords_en: ['fruit', 'food', 'peel', 'banana', 'orange', 'tangerine', 'mango'],
    keywords_ca: ['fruita', 'menjar', 'pela', 'plàtan', 'taronja', 'mandarina', 'mango'],
    description_es: 'Cualquier resto de fruta o verdura va al orgánico.',
    description_en: 'Any fruit or vegetable scraps go to organic waste.',
    description_ca: 'Qualsevol resta de fruita o verdura va a l\'orgànic.',
  },
  {
    name_es: 'Espina de pescado',
    name_en: 'Fish bone',
    name_ca: 'Espina de peix',
    container_type: 'OrganicContainer',
    keywords_es: ['pescado', 'comida', 'resto', 'hueso', 'espina', 'pez'],
    keywords_en: ['fish', 'food', 'leftover', 'bone', 'spine'],
    keywords_ca: ['peix', 'menjar', 'resta', 'os', 'espina'],
    description_es: 'Los restos de carne y pescado son orgánicos.',
    description_en: 'Meat and fish scraps are organic waste.',
    description_ca: 'Les restes de carn i peix són orgàniques.',
  },
  {
    name_es: 'Caja de pizza (sucia)',
    name_en: 'Pizza box (dirty)',
    name_ca: 'Caixa de pizza (bruta)',
    container_type: 'OrganicContainer',
    keywords_es: ['carton', 'pizza', 'grasa', 'aceite', 'caja', 'caja de pizza', 'cartón'],
    keywords_en: ['cardboard', 'pizza', 'grease', 'oil', 'box', 'pizza box'],
    keywords_ca: ['cartró', 'pizza', 'greix', 'oli', 'caixa', 'caixa de pizza'],
    description_es: 'Si el cartón está manchado de aceite o comida, no se puede reciclar como papel. Va al orgánico.',
    description_en: 'If the cardboard is stained with oil or food, it cannot be recycled as paper. Goes to organic waste.',
    description_ca: 'Si el cartró està tacat d\'oli o menjar, no es pot reciclar com a paper. Va a l\'orgànic.',
  },
  {
    name_es: 'Tapón de corcho',
    name_en: 'Cork stopper',
    name_ca: 'Tap de suro',
    container_type: 'OrganicContainer',
    keywords_es: ['vino', 'corcho', 'botella', 'tapon', 'tapón', 'cava', 'champan', 'champagne', 'champán'],
    keywords_en: ['wine', 'cork', 'bottle', 'stopper', 'champagne', 'cava'],
    keywords_ca: ['vi', 'suro', 'ampolla', 'tap', 'cava', 'xampany'],
    description_es: 'Si es corcho natural, al orgánico. Si es sintético/plástico, al amarillo.',
    description_en: 'If natural cork, to organic. If synthetic/plastic, to yellow container.',
    description_ca: 'Si és suro natural, a l\'orgànic. Si és sintètic/plàstic, al groc.',
  },
  {
    name_es: 'Posos de café',
    name_en: 'Coffee grounds',
    name_ca: 'Pòsit de cafè',
    container_type: 'OrganicContainer',
    keywords_es: ['cafe', 'filtro', 'infusion', 'posos', 'poso', 'café'],
    keywords_en: ['coffee', 'filter', 'infusion', 'grounds', 'tea'],
    keywords_ca: ['cafè', 'filtre', 'infusió', 'pòsit', 'te'],
    description_es: 'Tanto el café como el filtro de papel (o la bolsita de té) son orgánicos.',
    description_en: 'Both coffee and paper filter (or tea bag) are organic waste.',
    description_ca: 'Tant el cafè com el filtre de paper (o la bosseta de te) són orgànics.',
  },

  // --- PLASTIC (Amarillo - Envases) ---
  {
    name_es: 'Botella de agua',
    name_en: 'Water bottle',
    name_ca: 'Ampolla d\'aigua',
    container_type: 'PlasticContainer',
    keywords_es: ['plastico', 'envase', 'agua', 'bebida', 'botella', 'plástico'],
    keywords_en: ['plastic', 'container', 'water', 'drink', 'bottle'],
    keywords_ca: ['plàstic', 'envàs', 'aigua', 'beguda', 'ampolla'],
    description_es: 'Recuerda aplastarla para ahorrar espacio.',
    description_en: 'Remember to crush it to save space.',
    description_ca: 'Recorda aplanar-la per estalviar espai.',
  },
  {
    name_es: 'Lata de refresco',
    name_en: 'Soda can',
    name_ca: 'Llauna de refresc',
    container_type: 'PlasticContainer',
    keywords_es: ['lata', 'aluminio', 'refresco', 'cerveza'],
    keywords_en: ['can', 'aluminum', 'soda', 'beer'],
    keywords_ca: ['llauna', 'alumini', 'refresc', 'cervesa'],
    description_es: 'Las latas metálicas van al contenedor amarillo (envases).',
    description_en: 'Metal cans go to the yellow container (packaging).',
    description_ca: 'Les llaunes metàl·liques van al contenidor groc (envasos).',
  },
  {
    name_es: 'Tetra Brik',
    name_en: 'Tetra Pak',
    name_ca: 'Tetra Brik',
    container_type: 'PlasticContainer',
    keywords_es: ['leche', 'zumo', 'carton', 'brik', 'envase', 'bote', 'cartón'],
    keywords_en: ['milk', 'juice', 'cardboard', 'carton', 'container', 'tetra pak'],
    keywords_ca: ['llet', 'suc', 'cartró', 'brik', 'envàs'],
    description_es: 'Aunque parezca cartón, contiene plástico y aluminio. Va al amarillo.',
    description_en: 'Although it looks like cardboard, it contains plastic and aluminum. Goes to yellow.',
    description_ca: 'Encara que sembli cartró, conté plàstic i alumini. Va al groc.',
  },
  {
    name_es: 'Vaso de yogur',
    name_en: 'Yogurt cup',
    name_ca: 'Got de iogurt',
    container_type: 'PlasticContainer',
    keywords_es: ['yogur', 'plastico', 'lacteo', 'tapa', 'plástico', 'lácteo'],
    keywords_en: ['yogurt', 'plastic', 'dairy', 'lid'],
    keywords_ca: ['iogurt', 'plàstic', 'làctic', 'tapa'],
    description_es: 'El envase y la tapa metálica van al amarillo.',
    description_en: 'The container and metal lid go to yellow.',
    description_ca: 'L\'envàs i la tapa metàl·lica van al groc.',
  },
  {
    name_es: 'Bolsa de patatas fritas',
    name_en: 'Potato chips bag',
    name_ca: 'Bossa de patates fregides',
    container_type: 'PlasticContainer',
    keywords_es: ['bolsa', 'plastico', 'snack', 'envoltorio', 'patatas', 'fritas', 'chips', 'plástico'],
    keywords_en: ['bag', 'plastic', 'snack', 'wrapper', 'chips', 'crisps'],
    keywords_ca: ['bossa', 'plàstic', 'aperitiu', 'embolcall', 'patates', 'xips'],
    description_es: 'Los envoltorios plásticos y metalizados van al contenedor de envases.',
    description_en: 'Plastic and metallized wrappers go to the packaging container.',
    description_ca: 'Els embolcalls plàstics i metal·litzats van al contenidor d\'envasos.',
  },

  // --- PAPER (Azul) ---
  {
    name_es: 'Periódico',
    name_en: 'Newspaper',
    name_ca: 'Diari',
    container_type: 'PaperContainer',
    keywords_es: ['papel', 'diario', 'revista', 'noticias', 'periodico', 'periódico'],
    keywords_en: ['paper', 'newspaper', 'magazine', 'news'],
    keywords_ca: ['paper', 'diari', 'revista', 'notícies'],
    description_es: 'Papel limpio y seco.',
    description_en: 'Clean and dry paper.',
    description_ca: 'Paper net i sec.',
  },
  {
    name_es: 'Caja de zapatos',
    name_en: 'Shoe box',
    name_ca: 'Caixa de sabates',
    container_type: 'PaperContainer',
    keywords_es: ['carton', 'caja', 'embalaje', 'zapatos', 'calzado', 'cartón'],
    keywords_en: ['cardboard', 'box', 'packaging', 'shoes', 'footwear'],
    keywords_ca: ['cartró', 'caixa', 'embalatge', 'sabates', 'calçat'],
    description_es: 'Pliega la caja antes de tirarla.',
    description_en: 'Fold the box before throwing it away.',
    description_ca: 'Plega la caixa abans de llançar-la.',
  },
  {
    name_es: 'Folios usados',
    name_en: 'Used paper sheets',
    name_ca: 'Folis usats',
    container_type: 'PaperContainer',
    keywords_es: ['papel', 'hoja', 'documento', 'carta', 'folios', 'folios usados'],
    keywords_en: ['paper', 'sheet', 'document', 'letter', 'office paper'],
    keywords_ca: ['paper', 'full', 'document', 'carta', 'folis'],
    description_es: 'Quita clips o grapas si es posible, aunque no es imprescindible.',
    description_en: 'Remove clips or staples if possible, although not essential.',
    description_ca: 'Treu clips o grapes si és possible, encara que no és imprescindible.',
  },

  // --- GLASS (Verde) ---
  {
    name_es: 'Botella de vino',
    name_en: 'Wine bottle',
    name_ca: 'Ampolla de vi',
    container_type: 'GlassContainer',
    keywords_es: ['vidrio', 'botella', 'alcohol', 'cristal', 'vino'],
    keywords_en: ['glass', 'bottle', 'alcohol', 'wine'],
    keywords_ca: ['vidre', 'ampolla', 'alcohol', 'vi'],
    description_es: 'Solo vidrio. Quita el tapón (el corcho al orgánico, la chapa al amarillo).',
    description_en: 'Glass only. Remove the cap (cork to organic, metal cap to yellow).',
    description_ca: 'Només vidre. Treu el tap (el suro a l\'orgànic, la xapa al groc).',
  },
  {
    name_es: 'Tarro de mermelada',
    name_en: 'Jam jar',
    name_ca: 'Pot de melmelada',
    container_type: 'GlassContainer',
    keywords_es: ['bote', 'vidrio', 'conserva', 'mermelada', 'tarro'],
    keywords_en: ['jar', 'glass', 'preserve', 'jam'],
    keywords_ca: ['pot', 'vidre', 'conserva', 'melmelada'],
    description_es: 'El tarro al verde, la tapa metálica al amarillo.',
    description_en: 'Jar to green, metal lid to yellow.',
    description_ca: 'El pot al verd, la tapa metàl·lica al groc.',
  },

  // --- TEXTILE (Ropa) ---
  {
    name_es: 'Camiseta vieja',
    name_en: 'Old t-shirt',
    name_ca: 'Samarreta vella',
    container_type: 'TextileContainer',
    keywords_es: ['ropa', 'tela', 'algodon', 'trapo', 'camiseta', 'algodón'],
    keywords_en: ['clothes', 'fabric', 'cotton', 'rag', 't-shirt', 'shirt'],
    keywords_ca: ['roba', 'tela', 'cotó', 'drap', 'samarreta'],
    description_es: 'Si está en buen estado se reutiliza; si no, se recicla el tejido.',
    description_en: 'If in good condition it is reused; if not, the fabric is recycled.',
    description_ca: 'Si està en bon estat es reutilitza; si no, es recicla el teixit.',
  },

  // --- ELECTRIC (Punto Limpio / E-waste) ---
  {
    name_es: 'Secador de pelo',
    name_en: 'Hair dryer',
    name_ca: 'Assecador de cabell',
    container_type: 'ElectricContainer',
    keywords_es: ['electrodomestico', 'aparato', 'cable', 'electronica', 'secador', 'secador de pelo', 'electrónica'],
    keywords_en: ['appliance', 'device', 'cable', 'electronics', 'hair dryer', 'dryer'],
    keywords_ca: ['electrodomèstic', 'aparell', 'cable', 'electrònica', 'assecador'],
    description_es: 'Los aparatos eléctricos nunca van al contenedor normal. Llévalos al punto limpio.',
    description_en: 'Electrical appliances never go to regular bins. Take them to the recycling center.',
    description_ca: 'Els aparells elèctrics mai van al contenidor normal. Porta\'ls al punt net.',
  },

  // --- UNRECYCLABLE (Gris / Resto) ---
  {
    name_es: 'Copa de cristal rota',
    name_en: 'Broken crystal glass',
    name_ca: 'Copa de cristall trencada',
    container_type: 'Unrecyclable',
    keywords_es: ['cristal', 'roto', 'vajilla', 'vaso', 'copa', 'copa de cristal'],
    keywords_en: ['crystal', 'broken', 'tableware', 'glass', 'cup', 'drinking glass'],
    keywords_ca: ['cristall', 'trencat', 'vaixella', 'got', 'copa'],
    description_es: '¡OJO! El cristal (copas, vasos) tiene óxido de plomo y NO es vidrio. No va al verde, va al gris.',
    description_en: 'WARNING! Crystal (glasses, cups) has lead oxide and is NOT glass. Does not go to green, goes to gray.',
    description_ca: 'ATENCIÓ! El cristall (copes, gots) té òxid de plom i NO és vidre. No va al verd, va al gris.',
  },
  {
    name_es: 'Pañales',
    name_en: 'Diapers',
    name_ca: 'Bolquers',
    container_type: 'Unrecyclable',
    keywords_es: ['bebe', 'higiene', 'sucio', 'pañales', 'pañal', 'bebé'],
    keywords_en: ['baby', 'hygiene', 'dirty', 'diaper', 'nappy'],
    keywords_ca: ['bebè', 'higiene', 'brut', 'bolquer'],
    description_es: 'No son reciclables ni orgánicos. Van al contenedor de resto (gris).',
    description_en: 'Not recyclable or organic. Goes to residual waste bin (gray).',
    description_ca: 'No són reciclables ni orgànics. Van al contenidor de rebuig (gris).',
  },
  {
    name_es: 'Espejo roto',
    name_en: 'Broken mirror',
    name_ca: 'Mirall trencat',
    container_type: 'Unrecyclable',
    keywords_es: ['espejo', 'cristal', 'baño', 'roto'],
    keywords_en: ['mirror', 'crystal', 'bathroom', 'broken'],
    keywords_ca: ['mirall', 'cristall', 'bany', 'trencat'],
    description_es: 'Como el cristal de las copas, no se funde igual que las botellas. Al gris o punto limpio.',
    description_en: 'Like crystal glasses, it does not melt the same as bottles. To gray or recycling center.',
    description_ca: 'Com el cristall de les copes, no es fon igual que les ampolles. Al gris o punt net.',
  },
];
